# Generated by Django 3.1.7 on 2021-03-16 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_crud_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud_create',
            name='search',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crud_create',
            name='email',
            field=models.EmailField(default=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='crud_create',
            name='firstName',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='crud_create',
            name='lastName',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AlterModelTable(
            name='crud_create',
            table='crud__create',
        ),
    ]
