# Generated by Django 3.1.7 on 2021-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210316_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_create',
            name='email',
            field=models.EmailField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='crud_create',
            name='firstName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='crud_create',
            name='lastName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='crud_create',
            name='search',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
