# Generated by Django 3.1.7 on 2021-03-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210316_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_create',
            name='email',
            field=models.EmailField(default='', max_length=55),
        ),
    ]
