# Generated by Django 3.1.7 on 2021-03-16 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210316_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_create',
            name='date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
